name: Frontend Code Check

on:
  pull_request:
    branches:
      - main

jobs:
  structure-check:
    runs-on: ubuntu-latest

#repo checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#install dependencies
      - name: Install dependencies
        run: npm ci

#take build to find build errors
      - name: Build frontend
        run: npm run build
  
  trivy-secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy Secret Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: secret
          format: table
          exit-code: 1